# Generated by Django 4.2.30 on 2026-06-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('duracion', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=255)),
                ('calificacion', models.FloatField()),
                ('descripcion', models.TextField()),
                ('poster', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
